### ISSUE TITLE
how to use microcoap server

### ISSUE THREAD

**Issue by sarathsanthoss** [RIOT-OS/applications#23]
hi all,
can anyone teach me how to start microcoap-server example.....

if i am running on native as per read me file i'm getting the following result..i dont know after what to do? i also installed copper plugin and radvd,when i'm trying to ping in firefox it showing network unreachable..
LOG:
giri@giri:~/RIOT/examples/microcoap_server$ make term
/home/giri/RIOT/examples/microcoap_server/bin/native/microcoap_server.elf tap0
RIOT native interrupts/signals initialized.
LED_GREEN_OFF
LED_RED_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: UNKNOWN (builddir: /home/giri/RIOT))
RIOT microcoap example application
Configured network interfaces:
Iface 5 HWaddr: 76:50:44:76:11:44
MTU:1280 HL:64 RTR RTR_ADV

Source address length: 6
Link type: wired
inet6 addr: ff02::1/128 scope: local [multicast]
inet6 addr: fe80::7450:44ff:fe76:1144/64 scope: local
inet6 addr: ff02::1:ff76:1144/128 scope: local [multicast]
inet6 addr: ff02::2/128 scope: local [multicast]
inet6 addr: fc00::7450:44ff:fe76:1144/64 scope: global

Waiting for incoming UDP packet...

**Comment by sarathsanthoss** [comment]
Hi ,
Anybody there?

**Comment by gebart** [comment]
The question in your post relates to an example found in the main RIOT distribution. This repository is for some applications which are not part of the main distribution. You will likely get more answers on the riot-users mailing list (https://lists.riot-os.org/mailman/listinfo/users) or on IRC (`#riot-os` on Freenode)in the main RIOT repository (https://github.com/RIOT-OS/RIOT/issues)
