### ISSUE TITLE
sniffer: packet bursts get lost on pba-d-01-kw2x

### ISSUE THREAD

**Issue by pyropeter** [RIOT-OS/applications#32]
While trying to move away from our old econotag-based sniffer setup, I noticed that RIOTs sniffer seemed to drop some packets. I generated traffic on a RaspberryPi with Openlabs-Module using the following command:

    # ping -s 100 -c1 ff02::1%lowpan0

This requires 6lowpan to use fragmentation, resulting in two succesive IEEE 802.15.4 frames being transmitted.

While the econotag correctly receives both, the sniffer app on a pba-d-01-kw2x only receives the first frame. I guess this is some kind of race condition. How would I go about debugging this?

**Comment by PeterKietzmann** [comment]
I have no default procedure at hand but this might be related to [https://github.com/RIOT-OS/RIOT/issues/4822](https://github.com/RIOT-OS/RIOT/issues/4822). If so, please reopen that issue and report there.

**Comment by smlng** [comment]
Can you try to ping the nodes link-local unicast address instead of using multicast, also ensure that ACKREQ is enabled on the Raspbian.

**Comment by jowlo** [comment]
I can reproduce this bug on a different board, forked off of `frdm-kw41z` with pretty much identical hardware.

**Comment by miri64** [comment]
@jowlo @smlng @pyropeter can you test, if this is fixed by #34?
