### ISSUE TITLE
sniffer readme outdated

### ISSUE THREAD

**Issue by MichelRottleuthner** [RIOT-OS/applications#42]
The instructions on how to set up the sniffer are outdated.
I didn't look into details yet but the way how parameters need to be provided is clearly different.

**Comment by miri64** [comment]
Oops, I think I forgot that when providing https://github.com/RIOT-OS/applications/pull/37. Will fix ASAP.

**Comment by miri64** [comment]
> Will fix ASAP.

Among other fixes to that application's READMEs: See #43
